export interface Experience {
  id: string;
  image: string;
  title: string;
  price: number;
  duration: string;
  location: string;
  availableDates: string[]; // ISO date strings
  maxGuests: number;
  languages: string[];
  rating: number;
  category: string;
}

export const mockExperiences: Experience[] = [
  {
    id: '1',
    image: '/a.jpg',
    title: 'Seoul Chicken Adventure',
    price: 30,
    duration: '2.5 Hours',
    location: 'Seoul, Mapo-gu',
    availableDates: ['2025-12-20', '2025-12-21', '2025-12-22'],
    maxGuests: 4,
    languages: ['English', 'Korean'],
    rating: 4.8,
    category: 'Food & Drink',
  },
  {
    id: '2',
    image: '/a.jpg',
    title: 'Bite & Sight Tour',
    price: 55,
    duration: '3 Hours',
    location: 'Seoul, Jongno-gu',
    availableDates: ['2025-12-21', '2025-12-23'],
    maxGuests: 6,
    languages: ['English'],
    rating: 4.5,
    category: 'Tours',
  },
  {
    id: '3',
    image: '/a.jpg',
    title: 'Han River Night Kayak',
    price: 40,
    duration: '2 Hours',
    location: 'Seoul, Han River',
    availableDates: ['2025-12-20', '2025-12-24'],
    maxGuests: 2,
    languages: ['Korean', 'English'],
    rating: 4.9,
    category: 'Sports',
  },
  {
    id: '4',
    image: '/a.jpg',
    title: 'Traditional Tea Ceremony',
    price: 25,
    duration: '1.5 Hours',
    location: 'Seoul, Bukchon',
    availableDates: ['2025-12-22', '2025-12-25'],
    maxGuests: 4,
    languages: ['Korean', 'Japanese'],
    rating: 4.7,
    category: 'Culture',
  },
  {
    id: '5',
    image: '/a.jpg',
    title: 'K-Pop Dance Class',
    price: 35,
    duration: '2 Hours',
    location: 'Seoul, Gangnam',
    availableDates: ['2025-12-20', '2025-12-21', '2025-12-22', '2025-12-23'],
    maxGuests: 10,
    languages: ['English', 'Korean', 'Chinese'],
    rating: 4.6,
    category: 'Entertainment',
  },
  {
    id: '6',
    image: '/a.jpg',
    title: 'Hidden Alleyway Pub Crawl',
    price: 45,
    duration: '4 Hours',
    location: 'Seoul, Itaewon',
    availableDates: ['2025-12-20', '2025-12-21'],
    maxGuests: 8,
    languages: ['English', 'Spanish'],
    rating: 4.4,
    category: 'Nightlife',
  },
  {
    id: '7',
    image: '/a.jpg',
    title: 'Mountain Temple Stay',
    price: 80,
    duration: '1 Day',
    location: 'Gyeonggi-do',
    availableDates: ['2025-12-24', '2025-12-25'],
    maxGuests: 5,
    languages: ['Korean', 'English'],
    rating: 4.9,
    category: 'Nature',
  },
  {
    id: '8',
    image: '/a.jpg',
    title: 'Kimchi Making Workshop',
    price: 30,
    duration: '2 Hours',
    location: 'Seoul, Insadong',
    availableDates: ['2025-12-21', '2025-12-22'],
    maxGuests: 6,
    languages: ['English', 'Korean'],
    rating: 4.8,
    category: 'Food & Drink',
  },
  {
    id: '9',
    image: '/a.jpg',
    title: 'Palace Photography Tour',
    price: 60,
    duration: '3 Hours',
    location: 'Seoul, Gyeongbokgung',
    availableDates: ['2025-12-20', '2025-12-23'],
    maxGuests: 3,
    languages: ['English', 'Chinese'],
    rating: 4.7,
    category: 'Art',
  },
  {
    id: '10',
    image: '/a.jpg',
    title: 'Local Market Raid',
    price: 20,
    duration: '2 Hours',
    location: 'Seoul, Gwangjang Market',
    availableDates: ['2025-12-21', '2025-12-22'],
    maxGuests: 5,
    languages: ['Korean', 'English'],
    rating: 4.5,
    category: 'Food & Drink',
  },
  {
    id: '11',
    image: '/a.jpg',
    title: 'Pottery Making Class',
    price: 50,
    duration: '2.5 Hours',
    location: 'Seoul, Hongdae',
    availableDates: ['2025-12-23', '2025-12-24'],
    maxGuests: 4,
    languages: ['Korean', 'English'],
    rating: 4.6,
    category: 'Art',
  },
  {
    id: '12',
    image: '/a.jpg',
    title: 'Sunset Yacht Tour',
    price: 70,
    duration: '1.5 Hours',
    location: 'Seoul, Han River',
    availableDates: ['2025-12-20', '2025-12-21'],
    maxGuests: 10,
    languages: ['English', 'Korean'],
    rating: 4.9,
    category: 'Tours',
  },
  {
    id: '13',
    image: '/a.jpg',
    title: 'Korean Calligraphy',
    price: 25,
    duration: '1.5 Hours',
    location: 'Seoul, Insadong',
    availableDates: ['2025-12-22'],
    maxGuests: 6,
    languages: ['Korean', 'Chinese', 'Japanese'],
    rating: 4.3,
    category: 'Culture',
  },
  {
    id: '14',
    image: '/a.jpg',
    title: 'Street Food Fighter',
    price: 35,
    duration: '2.5 Hours',
    location: 'Seoul, Myeongdong',
    availableDates: ['2025-12-20', '2025-12-21', '2025-12-22'],
    maxGuests: 8,
    languages: ['English'],
    rating: 4.4,
    category: 'Food & Drink',
  },
  {
    id: '15',
    image: '/a.jpg',
    title: 'Namsan Hiking & Picnic',
    price: 15,
    duration: '3 Hours',
    location: 'Seoul, Namsan',
    availableDates: ['2025-12-21', '2025-12-22'],
    maxGuests: 6,
    languages: ['English', 'Korean'],
    rating: 4.7,
    category: 'Nature',
  },
  {
    id: '16',
    image: '/a.jpg',
    title: 'Perfume Making',
    price: 55,
    duration: '2 Hours',
    location: 'Seoul, Seongsu',
    availableDates: ['2025-12-23', '2025-12-24'],
    maxGuests: 4,
    languages: ['Korean', 'English'],
    rating: 4.8,
    category: 'Art',
  },
  {
    id: '17',
    image: '/a.jpg',
    title: 'Makgeolli Brewing',
    price: 45,
    duration: '3 Hours',
    location: 'Seoul, Mapo-gu',
    availableDates: ['2025-12-20', '2025-12-21'],
    maxGuests: 6,
    languages: ['English', 'Korean'],
    rating: 4.9,
    category: 'Food & Drink',
  },
  {
    id: '18',
    image: '/a.jpg',
    title: 'PC Bang Experience',
    price: 10,
    duration: '3 Hours',
    location: 'Seoul, Hongdae',
    availableDates: ['2025-12-20', '2025-12-21', '2025-12-22', '2025-12-23', '2025-12-24'],
    maxGuests: 2,
    languages: ['Korean', 'English'],
    rating: 4.2,
    category: 'Entertainment',
  },
  {
    id: '19',
    image: '/a.jpg',
    title: 'Hanbok Photoshoot',
    price: 40,
    duration: '2 Hours',
    location: 'Seoul, Bukchon',
    availableDates: ['2025-12-21', '2025-12-22'],
    maxGuests: 4,
    languages: ['English', 'Chinese'],
    rating: 4.6,
    category: 'Culture',
  },
  {
    id: '20',
    image: '/a.jpg',
    title: 'Gangnam Style Tour',
    price: 50,
    duration: '3 Hours',
    location: 'Seoul, Gangnam',
    availableDates: ['2025-12-20', '2025-12-22'],
    maxGuests: 8,
    languages: ['English'],
    rating: 4.3,
    category: 'Tours',
  },
  {
    id: '21',
    image: '/a.jpg',
    title: 'Temple Food Cooking',
    price: 65,
    duration: '3 Hours',
    location: 'Seoul, Jongno-gu',
    availableDates: ['2025-12-23'],
    maxGuests: 4,
    languages: ['Korean', 'English'],
    rating: 4.9,
    category: 'Food & Drink',
  },
  {
    id: '22',
    image: '/a.jpg',
    title: 'Retro Arcade Night',
    price: 15,
    duration: '2 Hours',
    location: 'Seoul, Euljiro',
    availableDates: ['2025-12-20', '2025-12-21'],
    maxGuests: 4,
    languages: ['Korean'],
    rating: 4.5,
    category: 'Entertainment',
  },
  {
    id: '23',
    image: '/a.jpg',
    title: 'Hangul Neon Sign Making',
    price: 60,
    duration: '2.5 Hours',
    location: 'Seoul, Euljiro',
    availableDates: ['2025-12-22', '2025-12-24'],
    maxGuests: 4,
    languages: ['Korean', 'English'],
    rating: 4.7,
    category: 'Art',
  },
  {
    id: '24',
    image: '/a.jpg',
    title: 'DMZ Day Trip',
    price: 90,
    duration: '8 Hours',
    location: 'Paju',
    availableDates: ['2025-12-21', '2025-12-23'],
    maxGuests: 10,
    languages: ['English'],
    rating: 4.8,
    category: 'Tours',
  },
  {
    id: '25',
    image: '/a.jpg',
    title: 'Korean BBQ Masterclass',
    price: 50,
    duration: '2 Hours',
    location: 'Seoul, Majang-dong',
    availableDates: ['2025-12-20', '2025-12-21'],
    maxGuests: 6,
    languages: ['English', 'Korean'],
    rating: 4.9,
    category: 'Food & Drink',
  },
  {
    id: '26',
    image: '/a.jpg',
    title: 'Bicycle City Tour',
    price: 25,
    duration: '3 Hours',
    location: 'Seoul, Yeouido',
    availableDates: ['2025-12-21', '2025-12-22'],
    maxGuests: 8,
    languages: ['English', 'Korean'],
    rating: 4.6,
    category: 'Sports',
  },
  {
    id: '27',
    image: '/a.jpg',
    title: 'Traditional Knot Making',
    price: 20,
    duration: '1.5 Hours',
    location: 'Seoul, Bukchon',
    availableDates: ['2025-12-23'],
    maxGuests: 5,
    languages: ['Korean', 'Japanese'],
    rating: 4.4,
    category: 'Culture',
  },
  {
    id: '28',
    image: '/a.jpg',
    title: 'Jazz Bar Hopper',
    price: 40,
    duration: '3 Hours',
    location: 'Seoul, Itaewon',
    availableDates: ['2025-12-20', '2025-12-21'],
    maxGuests: 4,
    languages: ['English'],
    rating: 4.7,
    category: 'Nightlife',
  },
  {
    id: '29',
    image: '/a.jpg',
    title: 'Meditation & Yoga',
    price: 30,
    duration: '1.5 Hours',
    location: 'Seoul, Forest Park',
    availableDates: ['2025-12-21', '2025-12-22'],
    maxGuests: 10,
    languages: ['Korean', 'English'],
    rating: 4.8,
    category: 'Sports',
  },
  {
    id: '30',
    image: '/a.jpg',
    title: 'Personal Color Analysis',
    price: 80,
    duration: '1.5 Hours',
    location: 'Seoul, Gangnam',
    availableDates: ['2025-12-22', '2025-12-23', '2025-12-24'],
    maxGuests: 1,
    languages: ['Korean', 'English', 'Chinese'],
    rating: 4.9,
    category: 'Beauty',
  },
];
